{
  pkgs,
  inputs,
  ...
}:
{
  # nixpkgs.config.cudaSupport = true;

  home.packages = with pkgs; [
    python3
    kitty
    trash-cli
    wl-clipboard
    hyprshot
    chezmoi
    kdePackages.filelight
    telegram-desktop
    spotify
    thunderbird
    pkgs.stable.bitwarden-desktop
    pkgs.stable.bitwarden-menu
    blender
    obsidian
    texlive.combined.scheme-full
    findutils.locate
    bluez
    blueman
    arduino-ide
    bottles
    obs-studio
    adwaita-icon-theme
    inkscape
    vlc
    rpi-imager
    nmap
    amneziawg-go
    amneziawg-tools
    android-studio
    steam
    pkgs.stable.aseprite
    inputs.nix-sweep.packages.${pkgs.stdenv.hostPlatform.system}.default
    scooter
    picocom
    rshell
    jetbrains.idea-oss
    bc
    xxd
    hexedit
    pkgs.stable.marktext
    gtk3
    gsettings-desktop-schemas
    libnotify
    zoom-us
    vlc
    kdePackages.gwenview
  ];
}
