### Program shortcut variables
$terminal = kitty
$term_launch = $terminal sh -c
$drun = gtk-launch
$runner = rofi -show combi -modes combi -combi-modes "window,drun,run"
$screenshot_region = hyprshot -m region --clipboard-only
$file_manager = nemo
$browser = $drun app.zen_browser.zen.desktop
